### ISSUE TITLE
Javelin is not installing

### ISSUE THREAD

**Issue by NicoGalvarino** [nye17/javelin#7]
After following the instructions to install javelin, it is not installing and doesn't appear in the list of installed packages of the environment. The installation supposedly ran ok, with no error messages (I'm attaching the message after the install command). Do you have any ideas about how to fix this? Thanks for the help!
[message_install_command.txt](https://github.com/nye17/javelin/files/9169043/message_install_command.txt)

**Comment by nye17** [comment]
As you said, the installation successfully finished with no error msgs. I'm not sure which "list" it has to appear in, as your output says it's installed into /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/javelin-0.35-py3.8.egg-info.

**Comment by nye17** [comment]
can you do an "import javelin" at least to see if there's any error msgs?

**Comment by NicoGalvarino** [comment]
I was referring to the list of packages in conda. “conda list” prints all the packages in my environment. Javelin appears in the conda list of my collaborators who have installed javelin before.

When I do import javelin in the iPython terminal, there’s no further error messages.

However, when running the demo.py file this message appears: ModuleNotFoundError: No module named ‘javelin.predict'

The same happens when I run the suggested commands from the “Running Javelin is Easy” section of the GitHub: ModuleNotFoundError: No module named 'javelin.zylc'

**Comment by nye17** [comment]
I don't use conda myself so I'm not sure whether codes installed via non-conda means would appear in the conda list output. Assuming it should, then it's probably because the directory you've installed JAVELIN into is not in the python path, which explains your latter problem of not finding proper modules from JAVELIN. This doesn't appear to be a JAVELIN problem but a local python environment setup problem I'm afraid. Is it possible for you to consult some local python guru first? and if not, can you list your commands going from installation to testing and the output of each command? Thanks.

**Comment by NicoGalvarino** [comment]
I understand! I'll ask someone about my python environments. I’ll let you know how it goes.

Thank you so much once again!
Nicolás
